dicoms/urls.py
from django.urls import path, include
from . import views

app_name = 'dicoms'

urlpatterns = [
    path('upload/',views.DicomFileUploadView.as_view(),name='dicom_upload'),
    path('my-uploads/',views.DicomFileMyUploadsListView.as_view(),name='dicom_my_uploads_list'),
    path('shared/',views.DicomFileSharedListView.as_view(),name='dicom_shared_list'),
    path('details/<int:pk>/',views.DicomFileDetailView.as_view(),name='dicom_detail'),
    path('update/<int:pk>/',views.DicomFileUpdateView.as_view(),name='dicom_update'),
    path('details/<int:pk>/post-comment',views.CommentSubmit.as_view(),name='comment_post'),
    path('details/delete-comment/<int:pk>',views.CommentDeleteView.as_view(),name='comment_delete'),
    path('delete/<int:pk>/', views.DicomFileDeleteView.as_view(),name='dicom_delete'),
    path('study/<int:pk>/', views.dicom_study_view, name='dicom_study'),

    path('patients/add',views.PatientRegisterView.as_view(), name='patient_add'),
    path('patients/details/<int:pk>/',views.PatientDetailView.as_view(),name='patient_detail'),
    path('patients/',views.PatientListView.as_view(), name='patients_list'),
    path('patients/delete/<int:pk>/',views.PatientDeleteView.as_view(),name='patient_delete'),
    path('patients/update/<int:pk>/',views.PatientUpdateView.as_view(),name='patient_update'),
    ]

medimageshub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from . import views

admin.site.site_header = "MedimagesHub administration"
admin.site.site_title = "MedimagesHub administration"
admin.site.index_title = "Admin dashboard"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('images/', include('dicoms.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('profile/<int:pk>/',views.UserDetailView.as_view(),name='user_detail'),
    path('users-list/',views.UserListView.as_view(), name='users_list'),
    path('about/',views.about_us_page_view, name='about_us'),
    path('contact/',views.contact_us_page_view, name='contact_us'),
    ]

dicoms/models.py
import os
from django.db import models
from .choices import Modality, Genders
from users.models import User
from django.urls import reverse 
from django_countries.fields import CountryField
from .validators import validate_file_extension

from medimageshub.storagebackends import PrivateMediaStorage
from django.core.files.storage import FileSystemStorage

class DicomFile(models.Model):

    file_url = models.FileField(
        #storage=PrivateMediaStorage(), 
        upload_to='dicoms/', validators=[validate_file_extension])

    file_title = models.CharField(max_length=256, blank=False)

    description = models.TextField(blank=True)

    picture_date = models.DateField(blank=False)
    upload_date = models.DateTimeField(auto_now_add=True)
    file_size = models.IntegerField(blank=False)
    

    owner = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=False, related_name='owner')
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE, blank=False)

    

    modality = models.CharField(choices = Modality.choices, blank=False, max_length=10)

    access = models.ManyToManyField(User, related_name='access', through='DicomFile_User', blank=True)

    def get_absolute_url(self):
        return reverse("dicoms:dicom_detail", kwargs={"pk": self.pk})

    def extension(self):
        name, extension = os.path.splitext(self.file_url.name)
        return extension

    def save(self, *args, **kwargs):
        self.file_size = self.file_url.size / 1024
        super(DicomFile, self).save(*args, **kwargs)
        

    def delete(self):
        self.file_url.delete(save=False)
        super(DicomFile, self).delete()
    
    def __str__(self):
        return f"{self.file_title}"

    class Meta:
        ordering = ['upload_date']




# Many to Many field to share files
class DicomFile_User(models.Model):
    dicomfile = models.ForeignKey(DicomFile, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    added_time = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['added_time']



class Patient(models.Model):
    first_name = models.CharField(max_length=128, blank=False)
    last_name = models.CharField(max_length=128, blank=False)

    main_doctor = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True)

    address = models.CharField(max_length=255, blank=False)
    postal_code = models.CharField(max_length=24, blank=False)
    city = models.CharField(max_length=64, blank=False)
    country = CountryField(blank=False)

    phone_nr = models.CharField(max_length=32, blank=True)

    birth_date = models.DateField(blank=False)
    gender = models.IntegerField(
        choices=Genders.choices,
        default=Genders.UNKNOWN,
        blank = False,
    )

    height = models.FloatField(blank=True)

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"


    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.city})"


    def get_absolute_url(self):
        return reverse("dicoms:patient_detail", kwargs={"pk": self.pk})


    class Meta:
        ordering = ['first_name', 'last_name']


class Comment(models.Model):
    author = models.ForeignKey('users.User', on_delete=models.CASCADE, null=True, blank=False)
    dicom_file = models.ForeignKey('DicomFile', on_delete=models.CASCADE, null=True, blank=False)
    comment = models.TextField(blank=False)
    comment_time = models.DateTimeField(auto_now_add=True)
    image_url = models.ImageField(
        #storage=PrivateMediaStorage(),
        upload_to='screenshots/', blank=True, null=True)

    def delete(self):
        self.image_url.delete(save=False)
        super(Comment, self).delete()

    class Meta:
        ordering = ['comment_time']

dicoms/forms.py
from .models import DicomFile, Comment, Patient
from django import forms
from datetime import datetime, timedelta
from .widgets import ShareWithUsersWidget, PatientSelectWidget, MainDoctorSelectWidget



class DicomUploadForm(forms.ModelForm):


    class Meta:
        model = DicomFile
        fields = ('file_title', 'file_url', 'picture_date', 'patient', 'modality', 'description', 'access')

        widgets = {
            'picture_date': forms.SelectDateWidget(years=range(datetime.now().year,1849,-1)),
            'access': ShareWithUsersWidget,
            'patient': PatientSelectWidget,
            }

        help_texts = {
            'access': 'Search by first name, last name or workplace',
            'patient': 'Search by first name, last name or city',
            'file_url': 'Upload .DCM or .ZIP file'
        }


class DicomShareForm(forms.ModelForm):

    class Meta:
        model = DicomFile
        fields = ('access',)
        widgets = {
            'access': ShareWithUsersWidget,
            }
        help_texts = {
            'access': 'Search by first name, last name or workplace',
        }



class PatientForm(forms.ModelForm):

    class Meta:
        model = Patient
        fields = '__all__'

        widgets = {
            'birth_date': forms.SelectDateWidget(years=range(datetime.now().year,1849,-1)),
            'main_doctor': MainDoctorSelectWidget,
            }
        help_texts = {
            'main_doctor': 'Search by first name, last name or workplace',
        }
    

    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)
        self.fields['height'].label = 'Height (in CMs)'


class PatientUpdateForm(forms.ModelForm):

    class Meta:
        model = Patient
        exclude = ('first_name','last_name')

        widgets = {
            'birth_date': forms.SelectDateWidget(years=range(datetime.now().year,1849,-1)),
            'main_doctor': MainDoctorSelectWidget,
            }
        help_texts = {
            'main_doctor': 'Search by first name, last name or workplace',
        }
    

    def __init__(self, *args, **kwargs):
        super(PatientUpdateForm, self).__init__(*args, **kwargs)
        self.fields['height'].label = 'Height (in CMs)'



class CommentForm(forms.ModelForm):
    http_method_names = ['get', 'post']

    class Meta:
        model = Comment
        fields = ('comment', 'image_url')
    
    def __init__(self, *args, **kwargs):
        """Save the request with the form so it can be accessed in clean_*()"""
        self.request = kwargs.pop('request', None)
        super(CommentForm, self).__init__(*args, **kwargs)

dicoms/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseForbidden
from django.urls import reverse, reverse_lazy
from django.views import View
from dicoms.filters import DicomFileMyUploadsListFilter, DicomFileSharedListFilter, PatientListFilter

from dicoms.forms import CommentForm, DicomUploadForm, PatientForm, DicomShareForm, PatientUpdateForm
from users.models import User
from .models import DicomFile, DicomFile_User, Patient, Comment
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView, FormView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import MultipleObjectMixin

import boto3
import medimageshub.settings as settings
from botocore.config import Config

import medimageshub.settings as settings

import json



### function to check if user has access to dicom file
def has_access_to_dicom(self):
    obj = self.get_object()
    owner = obj.owner == self.request.user
    access = self.request.user in obj.access.all()
    return owner or access


def can_edit_patient(self):
    obj = self.get_object()
    return obj.main_doctor == self.request.user


##### DCIOM Sudy View, where we use the Webnamics #####
@login_required
def dicom_study_view(request, pk):

    file_path = None
    if pk!=0:
        try:
            file_path = DicomFile.objects.get(id=pk).file_url.url
        except DicomFile.DoesNotExist:
            return render(request, "dicoms/image_not_found.html", context=context)
    
    context = {
        'file_path': file_path,
        'pk': pk,
    }
    return render(request, "dicoms/examine_image.html", context=context)



##### DICOM FILE VIEWS #####
class DicomFileUploadView(LoginRequiredMixin, CreateView):
    model = DicomFile
    form_class = DicomUploadForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(DicomFileUploadView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('dicoms:dicom_detail', kwargs={'pk': self.object.id})



class DicomFileUpdateView(UserPassesTestMixin, UpdateView):
    model = DicomFile
    form_class = DicomShareForm
    template_name = 'dicoms/dicomfile_update.html'


    def form_valid(self, form):
        return super(DicomFileUpdateView, self).form_valid(form)

    
    def test_func(self):
        return has_access_to_dicom(self)

    def get_success_url(self):
        return reverse_lazy('dicoms:dicom_detail', kwargs={'pk': self.object.id})



class DicomFileDeleteView(UserPassesTestMixin, DeleteView):
    # Requires model_confirm_delete.html template name
    model = DicomFile
    success_url = reverse_lazy('users:dashboard')

    
    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user




class DicomFileMyUploadsListView(LoginRequiredMixin, ListView):
    model = DicomFile
    template_name = 'dicoms/dicomfile_my_uploads.html'
    paginate_by = 25
    context_object_name = 'dicoms_list'
    filterset_class = DicomFileMyUploadsListFilter


    def get_queryset(self):
        order = self.request.GET.get('order')
        if order is None:
            order = 'file_title'
        queryset = DicomFile.objects.filter(owner=self.request.user).order_by(order)
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.distinct()


    def get_context_data(self, **kwargs):
        context = super(DicomFileMyUploadsListView, self).get_context_data(**kwargs)
        # Pass the filterset to the template - it provides the form.
        context['filterset'] = self.filterset
        return context





class DicomFileSharedListView(LoginRequiredMixin, ListView):
    model = DicomFile_User
    template_name = 'dicoms/dicomfile_shared_list.html'
    paginate_by = 25
    context_object_name = 'shared_list'
    filterset_class = DicomFileSharedListFilter
    
    def get_queryset(self):
        order = self.request.GET.get('order')
        if order is None:
            order = 'dicomfile__file_title'
        queryset = DicomFile_User.objects.filter(user=self.request.user).order_by(order)
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super(DicomFileSharedListView, self).get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context



class DicomFileDetailView(UserPassesTestMixin, DetailView, MultipleObjectMixin):
    model = DicomFile
    template_name = 'dicoms/dicomfile_detail.html'
    context_object_name = 'dicomfile'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        comments_list = Comment.objects.filter(dicom_file=self.get_object())
        context = super(DicomFileDetailView, self).get_context_data(object_list=comments_list, **kwargs)
        context['comment_form'] = CommentForm()
        return context
    
    def test_func(self):
        return has_access_to_dicom(self)







##### COMMENT VIEWS #####

class CommentSubmit(SingleObjectMixin, UserPassesTestMixin, FormView):
    model = DicomFile
    form_class = CommentForm
    template_name = 'dicoms/dicomfile_detail.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(CommentSubmit, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.dicom_file = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('dicoms:dicom_detail', kwargs={'pk': self.object.id})


    def test_func(self):
        return has_access_to_dicom(self)


class CommentDeleteView(UserPassesTestMixin, DeleteView):
    # Requires model_confirm_delete.html template name
    model = Comment

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

    def get_success_url(self):
        return reverse_lazy('dicoms:dicom_detail', kwargs={'pk': self.object.dicom_file.id})



##### PATIENT VIEWS #####

class PatientRegisterView(LoginRequiredMixin, CreateView): 
    model = Patient 
    form_class = PatientForm
    success_url = reverse_lazy('dicoms:patients_list')

    def form_valid(self, form):
        return super(PatientRegisterView, self).form_valid(form)


class PatientDetailView(LoginRequiredMixin, DetailView):
    model = Patient


class PatientListView(LoginRequiredMixin, ListView):
    model = Patient 
    context_object_name = 'patients_list'
    paginate_by = 25
    filterset_class = PatientListFilter
    
    def get_queryset(self):
        order = self.request.GET.get('order')
        if order is None:
            order = 'first_name'
        queryset = Patient.objects.order_by(order)
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super(PatientListView, self).get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context



class PatientUpdateView(UserPassesTestMixin, UpdateView):
    # Note! Uses model_form.html file as well
    # same form as CreateView
    model = Patient
    success_url = reverse_lazy('dicoms:patients_list')
    template_name = 'dicoms/patient_update.html'
    form_class = PatientUpdateForm


    def test_func(self):
        return can_edit_patient(self)
    

    def get_success_url(self):
        return reverse_lazy('dicoms:patient_detail', kwargs={'pk': self.object.id})



class PatientDeleteView(UserPassesTestMixin, DeleteView):
    # Requires model_confirm_delete.html template name
    model = Patient
    success_url = reverse_lazy('dicoms:patients_list')

    def test_func(self):
        return can_edit_patient(self)

dicoms/templates/dicoms/dicomfile_detail.html
{% extends 'base.html' %}

{% block title %}
DICOM file details for {{dicomfile.file_title}}
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>DICOM file {{dicomfile.file_title}}</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-5">
        <div class="general-container">
            <h3>Details for Dicom File</h3>
            
            <br><b>Title: {{dicomfile.file_title}}</b>
            <br>Uploaded by: <a href="{% url 'users:user_detail' pk=dicomfile.owner.id %}">{{dicomfile.owner.get_full_name}}</a>
            <br>Modality: {{dicomfile.modality}}
            <br>File size: {{ dicomfile.file_url.size|filesizeformat }}
            <br>Description: {{dicomfile.description}}
            <br>Extension: {{dicomfile.extension}}
            
            {% if dicomfile.extension|lower == '.zip' %}
            <p>
                <br><b>1.</b> Download the ZIP file below:
                <br><a href="{{dicomfile.file_url.url | safe}}">Download {{dicomfile.file_title}} ZIP file</a> 
                <br>(link valid only one hour, please refresh the page if the link is outdated)
                <br><b>2.</b> Open the DICOM viewer and upload the ZIP file on the DICOM Viewer by clicking "open" and "file" on the left navigation bar.
                <br><a href="{% url 'dicoms:dicom_study' pk=0 %}" target="_blank" class="btn btn-primary" role="button" data-bs-toggle="button">Open DICOM viewer</a></p>

            {% else %}
            <p><a href="{% url 'dicoms:dicom_study' pk=dicomfile.id %}" target="_blank"  class="btn btn-primary" role="button" data-bs-toggle="button">Examine image(s)</a></p>
            {% endif %}
            
            
            <h3> Shared with: </h3>
            <p id="shared-with-list">
            {% for shared_user in dicomfile.access.all %}
            <a href="{% url 'users:user_detail' pk=user.id %}">{{shared_user}}</a>, 
            {% endfor %}
            {% if user.id == dicomfile.owner.id %}
            <br><a href="{% url 'dicoms:dicom_update' pk=dicomfile.id %}" class="btn btn-primary" role="button" data-bs-toggle="button">Change who can view this</a>
            {% endif %}
            <h3> Add comment: </h3>
            <form action="{% url 'dicoms:comment_post' pk=dicomfile.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in comment_form %}
                <div class="field-wrapper">
                    {{ field.errors }}
                    {{ field|as_crispy_field }}
                </div>
            {% endfor %}
                <input type="submit" value='SUBMIT' class="btn btn-primary">
            </form>


            </div>
            {% if user.id == dicomfile.owner.id %}
            <p> <a class="btn btn-danger" href="{% url 'dicoms:dicom_delete' pk=dicomfile.id %}" role="button">Delete file</a>
            {% endif %}
    </div>
    <div class="col-md-7">
<div class="general-container">
<h3> Comments: </h3>
{% if not page_obj %}
No comments
{% endif %}
{% for comment in page_obj %}
<p>
<br><a href="{% url 'users:user_detail' pk=comment.author.id %}">{{comment.author.get_full_name}}</a>  Date: {{comment.comment_time}}
{% if comment.image_url %}<br><img src="{{ comment.image_url.url | safe}}" alt="Uploaded by {{comment.author}}" class="comment-image">{% endif %}
<br>{{comment.comment}}
    {% if user.id == comment.author.id %}
    <br><a href="{% url 'dicoms:comment_delete' pk=comment.id %}" class="text-danger">Delete comment</a>
    {% endif %}
</p>
{% endfor %}
</div>
{% if is_paginated %}
    {% include "includes/pagination.html" %}
{% endif %}
</div>
</div>

{% endblock %}

dicoms/templates/dicoms/dicomfile_form.html
{% extends 'base.html' %}

{% block title %}
Upload new DICOM file
{% endblock %}

{% block extraloads %}
{{ form.media.css }}
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>Upload new DICOM file</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-6">   
        <div class="general-container">
            <form enctype="multipart/form-data" method="POST" onsubmit="return confirm('Are you sure upload and share the resources to the selected persons (if any)?');">
                {% csrf_token %}
                {% for field in form %}
                <div class="field-wrapper">
                    {{ field.errors }}
                    {{ field|as_crispy_field }}
                    {% if field.name == 'patient' %}
                        <a href="{% url 'dicoms:patient_add' %}" target="_blank">Register new patient </a>
                        <br>
                        <br>
                    {% endif %}
                </div>
                {% endfor %}
                <input type="submit" value='UPLOAD' class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}

{% endblock %}

dicoms/templates/dicoms/image_not_found.html
{% extends 'base.html' %}

{% block title %}
ERROR: DICOM not found
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-12">
        <h1 class="text-center">ERROR: DICOM file(s) not found!</h1>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-md-1 text-center">
        <button onclick="history.back()">Go Back</button>
    </div>
</div>



{% endblock %}

dicoms/templates/dicoms/patient_detail.html
{% extends 'base.html' %}

{% block title %}
Patient details for {{patient.get_full_name}}
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h1>Details for patient {{patient.get_full_name}}</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-5">
		<div class="general-container">
			<div class="table-responsive">
				<table class="table">
					<tbody>
						<tr>
							<td>First name: </td>
							<td>{{patient.first_name}}</td>
						</tr>
						<tr>
							<td>Last name: </td>
							<td>{{patient.last_name}}</td>
						</tr>
						<tr>
							<td>Main doctor: </td>
							<td>{% if patient.main_doctor %}<a href="{% url 'users:user_detail' pk=patient.main_doctor.id %}">{{patient.main_doctor.get_full_name}} </a> {% else %}None{% endif %} </td>
						</tr>
						<tr>
							<td>Birth date: </td>
							<td>{{patient.birth_date}}</td>
						</tr>
						<tr>
							<td>Gender: </td>
							<td>{{patient.get_gender_display}}</td>
						</tr>
						<tr>
							<td>Height: </td>
							<td>{{patient.height}} CMs</td>
						</tr>
						<tr>
							<td>Country: </td>
							<td>{{patient.get_country_display}}</td>
						</tr>
						<tr>
							<td>City:  </td>
							<td>{{patient.city}}</td>
						</tr>
						<tr>
							<td>Postal code: </td>
							<td>{{patient.postal_code}}</td>
						</tr>
						<tr>
							<td>Address: </td>
							<td>{{patient.address}}</td>
						</tr>
						<tr>
							<td>Phone nr: </td>
							<td>{{patient.phone_nr}}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

{% if user.id == patient.main_doctor.id %}
<p> <a class="btn btn-primary" href="{% url 'dicoms:patient_update' pk=patient.id %}" role="button">Update patient</a>
{% endif %}

{% endblock %}

dicoms/templates/dicoms/patient_list.html
{% extends 'base.html' %}

{% block title %}
List of patients
{% endblock %}
{% load crispy_forms_tags %}
{% load my_tags %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-12">
        <h1>List of registered patients</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <div class="general-container">
<form method="get">
    {{ filterset.form|crispy }}
    <button type="submit" class="btn btn-primary">Search</button>
  </form>
</div>
<p><a class="btn btn-primary" href="{% url 'dicoms:patient_add' %}">Register new patient </a>
</div>
<div class="col-md-9">
    <div class="general-container">
        {% if patients_list %}
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th colspan="2">Patient</th>
                        <th colspan="2">Main doctor</th>
                        <th rowspan="2"><a href="?{% url_replace request 'order' 'birth_date' %}">Birth year</a>{% order_sign request 'birth_date' %}</th>
                        <th rowspan="2"><a href="?{% url_replace request 'order' 'gender' %}">Gender</a>{% order_sign request 'gender' %}</th>
                    </tr>
                    <tr>
                        <th><a href="?{% url_replace request 'order' 'first_name' %}">First name</a>{% order_sign request 'first_name' %}</th>
                        <th><a href="?{% url_replace request 'order' 'last_name' %}">Last name</a>{% order_sign request 'last_name' %}</th>
                        <th><a href="?{% url_replace request 'order' 'main_doctor__first_name' %}">First name</a>{% order_sign request 'main_doctor__first_name' %}</th>
                        <th><a href="?{% url_replace request 'order' 'main_doctor__last_name' %}">Last name</a>{% order_sign request 'main_doctor__last_name' %}</th>
                    </tr>
                    {% for patient in patients_list  %}
                    <tr>
                        <td><a href="{% url 'dicoms:patient_detail' pk=patient.id %}">{{patient.first_name}} </a></td>
                        <td><a href="{% url 'dicoms:patient_detail' pk=patient.id %}">{{patient.last_name}} </a></td>
                        <td>{% if patient.main_doctor %}<a href="{% url 'users:user_detail' pk=patient.main_doctor.id %}">{{patient.main_doctor.first_name}} </a> {% else %}N/A{% endif %} </td>
                        <td>{% if patient.main_doctor %}<a href="{% url 'users:user_detail' pk=patient.main_doctor.id %}">{{patient.main_doctor.last_name}} </a> {% else %}N/A{% endif %} </td>
                        <td>{{ patient.birth_date | date:"Y" }} </td>
                        <td>{{patient.get_gender_display}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
            {% else %}
            No patients found
            {% endif %}
            </div>
        </div>
    </div>

{% if is_paginated %}
    {% include "includes/pagination.html" %}
{% endif %}

{% endblock %}

dicoms/templates/dicoms/patient_update.html
{% extends 'base.html' %}

{% block title %}
Update patient
{% endblock %}

{% block extraloads %}
{{ form.media.css }}
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>Update patient</h1>
    </div>
</div>



<div class="row">
    <div class="col-md-6">   
        <div class="general-container">
            <p>Patient name: {{patient.get_full_name}}
            <form method="POST" onsubmit="return confirm('Are you sure to change patient details?');">
                {% csrf_token %}
                {% for field in form %}
                <div class="field-wrapper">
                    {{ field.errors }}
                    {{ field|as_crispy_field }}
                </div>
            {% endfor %}
                <p><input type="submit" value='UPDATE' class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{{ form.media.js }}

{% if user.id == patient.main_doctor.id %}
<p> <a class="btn btn-danger" href="{% url 'dicoms:patient_delete' pk=patient.id %}" role="button">Delete patient</a>
{% endif %}

{% endblock %}


