dicoms/urls.py
from django.urls import path, include
from . import views

app_name = 'dicoms'

urlpatterns = [
    path('upload/',views.DicomFileUploadView.as_view(),name='dicom_upload'),
    path('my-uploads/',views.DicomFileMyUploadsListView.as_view(),name='dicom_my_uploads_list'),
    path('shared/',views.DicomFileSharedListView.as_view(),name='dicom_shared_list'),
    path('details/<int:pk>/',views.DicomFileDetailView.as_view(),name='dicom_detail'),
    path('update/<int:pk>/',views.DicomFileUpdateView.as_view(),name='dicom_update'),
    path('details/<int:pk>/post-comment',views.CommentSubmit.as_view(),name='comment_post'),
    path('details/delete-comment/<int:pk>',views.CommentDeleteView.as_view(),name='comment_delete'),
    path('delete/<int:pk>/', views.DicomFileDeleteView.as_view(),name='dicom_delete'),
    path('study/<int:pk>/', views.dicom_study_view, name='dicom_study'),

    path('patients/add',views.PatientRegisterView.as_view(), name='patient_add'),
    path('patients/details/<int:pk>/',views.PatientDetailView.as_view(),name='patient_detail'),
    path('patients/',views.PatientListView.as_view(), name='patients_list'),
    path('patients/delete/<int:pk>/',views.PatientDeleteView.as_view(),name='patient_delete'),
    path('patients/update/<int:pk>/',views.PatientUpdateView.as_view(),name='patient_update'),
    ]

medimageshub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from . import views

admin.site.site_header = "MedimagesHub administration"
admin.site.site_title = "MedimagesHub administration"
admin.site.index_title = "Admin dashboard"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('images/', include('dicoms.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('profile/<int:pk>/',views.UserDetailView.as_view(),name='user_detail'),
    path('users-list/',views.UserListView.as_view(), name='users_list'),
    path('about/',views.about_us_page_view, name='about_us'),
    path('contact/',views.contact_us_page_view, name='contact_us'),
    ]

users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager ## A new class is imported. ##
from django.db import models
from datetime import datetime
from django.urls import reverse
from django_countries.fields import CountryField


class UserManager(BaseUserManager):
    """Model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Make and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Make and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Make and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    
# User model
class User(AbstractUser):
    """User model."""

    username = None
    email = models.EmailField(verbose_name='email address', unique=True)

    first_name = models.CharField(max_length=128, blank=False)
    last_name = models.CharField(max_length=128, blank=False)
    profession_title = models.CharField(max_length=255, blank=False)
    address = models.CharField(max_length=255, blank=False)
    postal_code = models.CharField(max_length=24, blank=False)
    city = models.CharField(max_length=64, blank=False)
    country = CountryField(blank=False)
    workplace = models.CharField(max_length=255, blank=False)
    phone_nr = models.CharField(max_length=32, blank=False)

    birth_date = models.DateField(blank=False)

    objects = UserManager()

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    
    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.profession_title} from {self.workplace})"


    def get_absolute_url(self):
        return reverse("user_details", kwargs={"pk": self.pk})

    

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'profession_title',
                        'country', 'city', 'postal_code','address',
                        'workplace', 'phone_nr', 'birth_date'] 
                        # Email & Password are required by default.

    class Meta:
        ordering = ['first_name', 'last_name']

users/forms.py
# users/forms.py

import hashlib
from django.contrib.auth.forms import UserCreationForm
from django.utils.crypto import get_random_string
from .models import User
from django import forms
from datetime import datetime, timedelta

users/views.py
# users/views.py
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from dicoms.models import DicomFile, Comment, DicomFile_User
from django.views.generic import DetailView , ListView
from django.db.models import Q

from users.filters import UserListFilter
from .models import User
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


@login_required
def dashboard_view(request):

    latest_dicoms = DicomFile_User.objects.filter(user=request.user.pk).order_by('-added_time')[:5]
    latest_comments = Comment.objects.filter(Q(dicom_file__access=request.user.pk) | Q(dicom_file__owner=request.user.pk)).order_by('-comment_time').distinct()[:5]

    context = {
        'latest_dicoms':latest_dicoms,
        'latest_comments':latest_comments,
    }

    return render(request,'users/dashboard.html', context=context)
    

def home_page_view(request):
    if request.user.is_authenticated:
        return redirect('users:dashboard')
    else:
        return redirect('login')


def about_us_page_view(request):
    return render(request,'users/about_us.html')



def contact_us_page_view(request):
    return render(request,'users/contact_us.html')



class UserDetailView(LoginRequiredMixin, DetailView):
    model = User


class UserListView(LoginRequiredMixin, ListView):
    model = User 
    context_object_name = 'users_list'
    paginate_by = 25
    filterset_class = UserListFilter
    
    def get_queryset(self):
        order = self.request.GET.get('order')
        if order is None:
            order = 'first_name'
        queryset = User.objects.order_by(order)
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context

users/templates/users/about_us.html
<!--users/templates/users/dashboard.html-->

{% extends 'base.html' %}

{% block title %}
About us
{% endblock %}

{% load static %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-12">
        <h1>About us</h1>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="general-container">
            <h3>Welcome To MedimagesHub!</h3>
            <p>MedimagesHub is a platform for sharing and viewing medical images build by computer science engineering students
            from UiT The Arctic University of Norway. This project is built as their bachelor thesis project, so it's not meant for
            public use, but just for testing.
            
            <p>Here you can upload, share them and examine the medical images as DICOM files or folders.
            It's a closed plattorm, so not anyone can register here. This is to protect the integrity of the platform,
            make sure only real medical professionals use it.
        
            <p>To start using this system you can contact us at {% url 'users:contact_us' %}
        
            <p>Thanks For Visiting Our Site
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/contact_us.html
<!--users/templates/users/dashboard.html-->

{% extends 'base.html' %}

{% block title %}
home
{% endblock %}

{% load static %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-12">
        <h1>Contact us</h1>
        <div class="general-container">
         You can contact us at bla bla bla [email address hidden]
        </div>
    </div>
</div>



{% endblock %}

users/templates/users/dashboard.html
<!--users/templates/users/dashboard.html-->

{% extends 'base.html' %}

{% block title %}
dashboard
{% endblock %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-md-12">
        <h1>Dashboard for {{ user.get_full_name }}</h1>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="general-container">
            <h4 class="table-header">Latest files shared</h4>
            {% if latest_dicoms %}
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <th>Name</th>
                            <th>Patient name</th>
                            <th>Picture date</th>
                            <th>Shared time</th>
                            <th>File type</th>
                        </tr>
                        {% for dicom in latest_dicoms  %}
                        <tr>
                            <td><a href="{% url 'dicoms:dicom_detail' pk=dicom.dicomfile.id %}">{{dicom.dicomfile.file_title}}</a></td>
                            <td><a href="{% url 'dicoms:patient_detail' pk=dicom.dicomfile.patient.id %}">{{dicom.dicomfile.patient.get_full_name}}</a></td>
                            <td>{{dicom.dicomfile.picture_date}}</td>
                            <td>{{dicom.added_time}}</td>
                            <td>{{dicom.dicomfile.extension}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            No shared files
            {% endif %}
        </div>
        
    </div>
    <div class="col-md-6">
        
        <div class="general-container">
            
            <h4 class="table_header">Latest comments</h4>
            {% if latest_comments %}
                {% for comment in latest_comments %}
                <div class="comments">
                <p>
                <br>DICOM file name: <a href="{% url 'dicoms:dicom_detail' pk=comment.dicom_file.id %}">{{comment.dicom_file.file_title}}</a>
                <br>Author: <a href="{% url 'users:user_detail' pk=comment.author.id %}">{{comment.author.get_full_name}}</a>  Date: {{comment.comment_time}}
                {% if comment.image_url %}<br><img src="{{ comment.image_url.url | safe}}" alt="Uploaded by {{comment.author}}"  class="comment-image">{% endif %}
                <br>{{comment.comment}}
                    {% if user.id == comment.author.id %}
                    <br><a href="{% url 'dicoms:comment_delete' pk=comment.id %}" class="text-danger">Delete comment</a>
                    {% endif %}
                </p>
            </div>
                {% endfor %}
                {% else %}
                No comments
                {% endif %}
                
        </div>
            </div>
</div>



{% endblock %}

users/templates/users/home.html
<!--users/templates/users/dashboard.html-->

{% extends 'base.html' %}

{% block title %}
home
{% endblock %}

{% load static %}

{% block content %}
<h1>This is the home page, welcome to Medimages Hub</h1>
<div class="general-container">
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

{% endblock %}

users/templates/users/user_detail.html
{% extends 'base.html' %}

{% block title %}
User details for {{user.get_full_name}}
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h1>Details for {{user.get_full_name}}</h1>
	</div>
</div>

<div class="row">
	<div class="col-md-5">
		<div class="general-container">
			<div class="table-responsive">
				<table class="table">
					<tbody>
						<tr>
							<td>First name: </td>
							<td>{{user.first_name}}</td>
						</tr>
						<tr>
							<td>Last name: </td>
							<td>{{user.last_name}}</td>
						</tr>
						<tr>
							<td>Profession title: </td>
							<td>{{user.profession_title}}</td>
						</tr>
						<tr>
							<td>Workplace: </td>
							<td>{{user.workplace}}</td>
						</tr>
						<tr>
							<td>Country: </td>
							<td>{{user.get_country_display}}</td>
						</tr>
						<tr>
							<td>City: </td>
							<td>{{user.city}}</td>
						</tr>
						<tr>
							<td>Postal code: </td>
							<td>{{user.postal_code}}</td>
						</tr>
						<tr>
							<td>Address: </td>
							<td>{{user.address}}</td>
						</tr>
						<tr>
							<td>Phone nr: </td>
							<td>{{user.phone_nr}}</td>
						</tr>
						<tr>
							<td>Birth date: </td>
							<td>{{user.birth_date}}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<br><a class="btn btn-primary" href="{% url 'password_change' %}">Change password</a>
	</div>
</div>





{% endblock %}

users/templates/users/user_list.html
{% extends 'base.html' %}

{% block title %}
List of users
{% endblock %}
{% load crispy_forms_tags %}
{% load my_tags %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-12">
        <h1>List of users of this system</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <div class="general-container">
            <form method="get">
                {{ filterset.form|crispy }}
                <button type="submit" class="btn btn-primary">Search</button>
              </form>
            
            </div>
        </div>
        <div class="col-md-9">
            <div class="general-container">
                {% if user %}
            <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th><a href="?{% url_replace request 'order' 'first_name' %}">First name</a>{% order_sign request 'first_name' %}</th>
                        <th><a href="?{% url_replace request 'order' 'last_name' %}">Last name</a>{% order_sign request 'last_name' %}</th>
                        <th><a href="?{% url_replace request 'order' 'profession_title' %}">Profession title</a>{% order_sign request 'profession_title' %}</th>
                        <th><a href="?{% url_replace request 'order' 'workplace' %}">Workplace</a>{% order_sign request 'workplace' %}</th>
                        <th><a href="?{% url_replace request 'order' 'country' %}">Country</a>{% order_sign request 'country' %}</th>
                        <th><a href="?{% url_replace request 'order' 'city' %}">City</a>{% order_sign request 'city' %}</th>
                    </tr>
                    {% for user in users_list %}
                    <tr>
                        <td><a href="{% url 'users:user_detail' pk=user.id %}">{{user.first_name}} </a></td>
                        <td><a href="{% url 'users:user_detail' pk=user.id %}">{{user.last_name}} </a></td>
                        <td>{{user.profession_title}}</td>
                        <td>{{user.workplace}}</td>
                        <td>{{user.get_country_display}}</td>
                        <td>{{user.city}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
            {% else %}
            No user found
            {% endif %}
            </div>
    </div>
</div>



{% if is_paginated %}
    {% include "includes/pagination.html" %}
{% endif %}

{% endblock %}