dicoms/urls.py
from django.urls import path, include
from . import views

app_name = 'dicoms'

urlpatterns = [
    path('upload/',views.DicomFileUploadView.as_view(),name='dicom_upload'),
    path('my-uploads/',views.DicomFileMyUploadsListView.as_view(),name='dicom_my_uploads_list'),
    path('shared/',views.DicomFileSharedListView.as_view(),name='dicom_shared_list'),
    path('details/<int:pk>/',views.DicomFileDetailView.as_view(),name='dicom_detail'),
    path('update/<int:pk>/',views.DicomFileUpdateView.as_view(),name='dicom_update'),
    path('details/<int:pk>/post-comment',views.CommentSubmit.as_view(),name='comment_post'),
    path('details/delete-comment/<int:pk>',views.CommentDeleteView.as_view(),name='comment_delete'),
    path('delete/<int:pk>/', views.DicomFileDeleteView.as_view(),name='dicom_delete'),
    path('study/<int:pk>/', views.dicom_study_view, name='dicom_study'),

    path('patients/add',views.PatientRegisterView.as_view(), name='patient_add'),
    path('patients/details/<int:pk>/',views.PatientDetailView.as_view(),name='patient_detail'),
    path('patients/',views.PatientListView.as_view(), name='patients_list'),
    path('patients/delete/<int:pk>/',views.PatientDeleteView.as_view(),name='patient_delete'),
    path('patients/update/<int:pk>/',views.PatientUpdateView.as_view(),name='patient_update'),
    ]

medimageshub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from . import views

admin.site.site_header = "MedimagesHub administration"
admin.site.site_title = "MedimagesHub administration"
admin.site.index_title = "Admin dashboard"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('images/', include('dicoms.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('profile/<int:pk>/',views.UserDetailView.as_view(),name='user_detail'),
    path('users-list/',views.UserListView.as_view(), name='users_list'),
    path('about/',views.about_us_page_view, name='about_us'),
    path('contact/',views.contact_us_page_view, name='contact_us'),
    ]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mainstyle.css' %}" >

    <title>{% block title %}{% endblock %} - MedimagesHub</title>
    {% block extraloads %}{% endblock %}



</head>
<body>
  <div id="page-container">
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #0088AA;">
    <a class="navbar-brand" href="{% url 'users:home' %}">MedImagesHub</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:home' %}"> Dashboard </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'dicoms:dicom_upload' %}"> Upload image </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'dicoms:dicom_my_uploads_list' %}"> My uploads </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'dicoms:dicom_shared_list' %}"> Shared images </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'dicoms:patient_add' %}"> New patient </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'dicoms:patients_list' %}"> Patients list </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:users_list' %}"> Users list </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:user_detail' pk=user.id %}">My profile</a>
      </li>
      {% if user.is_staff %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin dashboard</a>
    </li>
      {% endif %}
      </ul>
      <ul class="navbar-nav text-right">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
    </ul>
    {% else %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
    </ul>
    <ul class="navbar-nav text-right">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}"> Login </a>
      </li>
    </ul>
    {% endif %}
    </div>
  </nav>
        <div class="container">
    {% block content %}



    {% endblock %}
          </div>

<footer class="mt-auto">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: #0088AA;">
        © 2022 Copyright:
          <a class="text-dark" href={% url 'users:home' %}>Medimages.com</a>
        - <a class="text-dark" href="{% url 'users:about_us' %}"> About us </a>
        - <a class="text-dark" href="{% url 'users:contact_us' %}"> contact us </a>

  <!-- Copyright -->
</div>
</footer>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>